import { defineConfig } from 'tsup';

export default defineConfig({
  clean: true,
  dts: true,
  entry: {
    'agent-files': 'src/agent-files.ts',
    chatbot: 'src/chatbot.ts',
    client: 'src/client.ts',
    chunking: 'src/chunking.ts',
    index: 'src/index.ts',
    'provider-runtime': 'src/internal/provider-runtime.ts',
    errors: 'src/errors.ts',
    models: 'src/models/index.ts',
    pii: 'src/pii.ts',
    'providers-anthropic': 'src/providers/anthropic.ts',
    'providers-gemini': 'src/providers/gemini.ts',
    'providers-openai': 'src/providers/openai.ts',
    retrieval: 'src/retrieval.ts',
    'session-api': 'src/session-api.ts',
    'session-store': 'src/session-store.ts',
    utils: 'src/utils/index.ts',
  },
  format: ['esm', 'cjs'],
  minifyIdentifiers: false,
  minifySyntax: false,
  minifyWhitespace: true,
  external: [
    '#provider-runtime',
    'unified-llm-client/errors',
    'unified-llm-client/models',
    'unified-llm-client/session-api',
    'unified-llm-client/session-store',
    'unified-llm-client/utils',
  ],
  platform: 'neutral',
  sourcemap: true,
  splitting: false,
  target: 'node18',
  treeshake: true,
});
