import type { ModelInfo } from '../types.js';

export type RawModelRegistry = Record<string, Omit<ModelInfo, 'id'>>;

// Keep src/models/prices.json in the repo as the human-editable price file.
// This typed mirror keeps declaration builds stable across bundlers.
export const defaultModelPrices = {
  'claude-sonnet-4-6': {
    cacheReadPrice: 0.3,
    cacheWritePrice: 3.75,
    contextWindow: 200000,
    inputPrice: 3,
    lastUpdated: '2026-03-15',
    outputPrice: 15,
    provider: 'anthropic',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  'claude-haiku-4-5': {
    cacheReadPrice: 0.08,
    cacheWritePrice: 1,
    contextWindow: 200000,
    inputPrice: 0.8,
    lastUpdated: '2026-03-15',
    outputPrice: 4,
    provider: 'anthropic',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  'claude-opus-4-6': {
    cacheReadPrice: 1.5,
    cacheWritePrice: 18.75,
    contextWindow: 200000,
    inputPrice: 15,
    lastUpdated: '2026-03-15',
    outputPrice: 75,
    provider: 'anthropic',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  'gpt-5.4': {
    cacheReadPrice: 1.25,
    contextWindow: 128000,
    inputPrice: 2.5,
    lastUpdated: '2026-03-15',
    outputPrice: 10,
    provider: 'openai',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  'gpt-5.4-mini': {
    cacheReadPrice: 0.2,
    contextWindow: 128000,
    inputPrice: 0.4,
    lastUpdated: '2026-03-15',
    outputPrice: 1.6,
    provider: 'openai',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  'gpt-5.4-nano': {
    cacheReadPrice: 0.05,
    contextWindow: 128000,
    inputPrice: 0.1,
    lastUpdated: '2026-03-15',
    outputPrice: 0.4,
    provider: 'openai',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: false,
  },
  'gpt-4o': {
    cacheReadPrice: 1.25,
    contextWindow: 128000,
    inputPrice: 2.5,
    lastUpdated: '2026-03-15',
    outputPrice: 10,
    provider: 'openai',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  'gpt-4o-mini': {
    cacheReadPrice: 0.075,
    contextWindow: 128000,
    inputPrice: 0.15,
    lastUpdated: '2026-03-15',
    outputPrice: 0.6,
    provider: 'openai',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  o3: {
    cacheReadPrice: 2.5,
    contextWindow: 200000,
    inputPrice: 10,
    lastUpdated: '2026-03-15',
    outputPrice: 40,
    provider: 'openai',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  'gemini-2.5-pro': {
    contextWindow: 1000000,
    inputPrice: 1.25,
    lastUpdated: '2026-03-15',
    outputPrice: 10,
    provider: 'google',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  'gemini-2.5-flash': {
    contextWindow: 1000000,
    inputPrice: 0.075,
    lastUpdated: '2026-03-15',
    outputPrice: 0.3,
    provider: 'google',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  'gemini-2.5-flash-lite': {
    contextWindow: 1000000,
    inputPrice: 0.015,
    lastUpdated: '2026-03-15',
    outputPrice: 0.06,
    provider: 'google',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  'gemini-3.1-pro-preview': {
    contextWindow: 1048576,
    inputPrice: 2,
    lastUpdated: '2026-04-25',
    outputPrice: 12,
    provider: 'google',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  'gemini-3.1-flash-lite-preview': {
    contextWindow: 1048576,
    inputPrice: 0.25,
    lastUpdated: '2026-04-25',
    outputPrice: 1.5,
    provider: 'google',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  'gemini-embedding-2': {
    contextWindow: 8192,
    embeddingDimensions: {
      default: 3072,
      max: 3072,
      recommended: [768, 1536, 3072],
    },
    inputPrice: 0,
    kind: 'embedding',
    lastUpdated: '2026-04-24',
    maxInputTokens: 8192,
    outputPrice: 0,
    provider: 'google',
    supportedInputModalities: ['audio', 'document', 'image', 'text'],
    supportsStreaming: false,
    supportsTools: false,
    supportsVision: false,
  },
} satisfies RawModelRegistry;
